### ISSUE TITLE
Dynamic Graphs

### ISSUE THREAD

**Issue by TheAkashain** [simoninireland/epydemic#5]
I am currently reviewing existing Python 3 packages for simulating disease spread, and have come upon this in my search.

Thus, my question is, when "addition-deletion" networks are mentioned, would thus allow for a simple dynamic graph (possibly through the DyNetX package)? And, if so, would this be functional with a more complex disease type (SEIQR where I can be symptomatic or asymptomatic and Q refers to quarantined)?

**Comment by simoninireland** [comment]
Not used DyNetX before, but yes, one can certainly combine addition-deletion with any compartmented model (using multiple inheritance), and one can certainly write a compartmented model that includes quarantine.

I presume you're intending to have some individuals in E transfer to I and some to Q? If the Q nodes are entirely quarantined then they're essentially removed (R) which would essentially just increase the effective removal probability. You could also treat transfer to Q as an opportunity to rewire the node's links with some probability. In this case you need to be careful to make sure that the rewiring operation is written carefully so that it scales properly.

We've been looking at two similar scenarios to this, one to see how key workers are affected by disease transmission from a general population, and one looking at better models of human contact networks and social distancing.

Happy to help or discuss further.

**Comment by TheAkashain** [comment]
@simoninireland This answers my question quite well, thank you!
This makes me curious though, let's say we wanted to define 2 states of the population: 1 "workday" state where people's connections are with their household and business, and 1 "weekend / holiday" state where people have a lot of sudden pseudo-random connections (beach trips, stores, etc). Is there any way you would propose doing this effectively? I can easily create each population network using NetworkX, but switching between them is my current concern. (This is essentially what I would want to do with my dynamic graph)
My best idea right now is to have a condition on each of the links such that if "day = workday" certain links are checked, and if "day = weekend" other connections are checked, though I'm not 100% sure how to implement this.

**Comment by simoninireland** [comment]
Hmmm, nice problem....:-)

You could do this as a rewiring operation every weekend, but that'd be very expensive. Our experience is that adaptive network rewiring is quite tricky to code scalably: the problem is when you start searching the network for nodes that have some property to rewire to. It works OK if you use loci to keep track of the sets, as they get maintained at every event so you avoid the O(n) searching.

I think in your case you could set up a multiplex network to do the job. Build the "workday" links first, then the "weekend" links, and put an attribute on each one to denote which set they belong to. Keep two loci of SI edges, one for workday-labelled and one for weekend-labelled. Then switch between the two when picking an edge to transmit the disease over depending on a state variable. Think of the edges as having different "colours", and use one colour for each time period.

There's going to be a delicate part to this when you're selecting events in the stochastic (Gillespie) dynamics: what happens if the time to the next event crosses a boundary from workday to weekend? You can get round this easily by using the synchronous dynamics, which might be a bit slower but avoids some possibly awkward corner cases. You'd probably want to sub-class SynchronousDynamics to make it "colour-aware", rather than putting the choice into the SIR (of whatever) model class, again to avoid messing up the statistical properties. 

I've been writing about some of these issues as a way of introducing people to epidemic modelling:

https://simoninireland.github.io/introduction-to-epidemics/index.html

Still very much a work in progress, but I'm in the process of writing the chapters about SEIR and social distancing. (Comments welcome :-).) Once this is done I have some ideas to improve epydemic's speed, which will hopefully make it easier to look at larger and more adaptive models.

Hope this all helps :-) -- happy to discuss further

**Comment by TheAkashain** [comment]
@simoninireland Thank you for your quick reply! 

I'll definitely try this out and forward any necessary information I get. For now, though, I need to learn how to use the package well (I'm learning this alongside EoN, and I plan on seeing if the results match, as then it offers the maximum confirmation in my results, and the ability to diagnose problems easier). Thus, I am wondering if you have a link to example SEIR code? Preferably code that could be modified to turn the SEIR model into SE(Symptomatic / Asymptomatic)R, as that is what my research is focused on!

**Comment by simoninireland** [comment]
Just uploaded a new version (0.99.8) that has an SEIR process. It has parameters to change S-E and S-I infection probabilities independently. Let me knoe how you get on :-).

**Comment by TheAkashain** [comment]
I just noticed I forget to close this issue, my bad! I'll check everything out and keep you updated as I discover new things!
