### ISSUE TITLE
Error when running complete network model

### ISSUE THREAD

**Issue by jzicker** [simoninireland/epydemic#8]
tried running the complete network example and almost got it to work.   Here is error from last cell to run simulation and plot

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-4ee9f04c4a89> in <module>
     11 
     12 # run the corresponding simulation
---> 13 (sim_ts, sim_sss, sim_iss, sim_rss) = network_sir(T, g, pInfected, pInfect, pRemove)
     14 ax.plot(sim_ts, sim_sss, 'rs', label='suceptible (simulation)')
     15 ax.plot(sim_ts, sim_iss, 'gs', label='infected (simulation)')

<ipython-input-3-80183246f1b2> in network_sir(T, g, pInfected, pInfect, pRemove)
     16 
     17     # extract the time series
---> 18     results = e.experimentalResults()[MonitoredSIR.TIMESERIES]
     19     ts = results[MonitoredSIR.OBSERVATIONS]
     20     sss = results[epydemic.SIR.SUSCEPTIBLE]

~/opt/anaconda3/envs/Epi-Network/lib/python3.8/site-packages/epydemic/networkdynamics.py in experimentalResults(self)
     84 
     85         :returns: the results of the process'''
---> 86         return self._process.results()
     87 
     88 

~/opt/anaconda3/envs/Epi-Network/lib/python3.8/site-packages/epydemic/compartmentedmodel.py in results(self)
    333         # add size of each compartment
    334         for c in self.compartments():
--> 335             rc[c] = len(self.compartment(c))
    336         return rc
    337 

~/opt/anaconda3/envs/Epi-Network/lib/python3.8/site-packages/epydemic/compartmentedmodel.py in compartment(self, c)
    322         :param c: the compartment
    323         :returns: a collection of nodes'''
--> 324         return [ n for n in self.network().nodes() if self.getCompartment(n) == c ]
    325 
    326     def results(self) -> Dict[str, Any]:

AttributeError: 'NoneType' object has no attribute 'nodes'

**Comment by simoninireland** [comment]
Hiya,

That looks like there's no network been provided to the experiment class -- which code are you trying to run? If you send me a pointer we'll get it sorted out.

Thanks for your interest in in epydemic :-)

-- Simon

**Comment by jzicker** [comment]
Here is the link to the section in the online book.

**Comment by simoninireland** [comment]
Ah, I see: you're running against a newer version of epydemic that the book's code. epydemic changed as a result of writing the book (and got a **_lot_** faster as a result), but it does mean some changes to the code. I'm in the process of changing the book to match the new library: in the meantime I've changed the Makefile in the repo to use library versions that I know work -- if you check the project out again it should work fine. Hopefully that should fix it -- let me know if not.

Thanks for you interest in epydemic, and my book.

Cheers,

-- Simon

**Comment by jzicker** [comment]
Hi,
Thanks for you help on this.   I must be doing something wrong on checkout.  Do you mind posting the specific git checkout command?

thank you,
John

**Comment by simoninireland** [comment]
Great! -- thanks for reporting this, and hanging-in wile I fixed it :-).

Cheers,

-- Simon

**Comment by FeynmanDNA** [comment]
Hi i encountered the same problem, and thanks to the discussions above, i also managed to get the book example to work!

Here are some extra information that I found useful:
1. the "appropriate versions epydemic and epyc" are specified in `known-good-requirements.txt` in https://github.com/simoninireland/introduction-to-epidemics/blob/master/known-good-requirements.txt
2. the versions are `epyc==0.99.3` and  `epydemic-0.99.8`

Just curious, if we want to use the faster new version of epydemic in network model (e.g. https://simondobson.org/introduction-to-epidemics/network.html), where can we find example usage like in the book?

Many thanks!

**Comment by simoninireland** [comment]
Hi, sorry for the delay in replying :-). Thanks for your interest in epydemic.

The later versions of epydemic are indeed faster and better than the code I presented in the book: in fact it's better **because** of the book, which changed how we thought about doing simulations.

The changes aren't enormous at the user level:

- there's not a ProcessSequence class you can use instead of multiple inheritance to get monitored behaviour, described in a [cookbook recipe](https://pyepydemic.readthedocs.io/en/latest/cookbook/monitoring-progress.html) 
- we introduced network generators to make it easier to build [classes of networks](https://pyepydemic.readthedocs.io/en/latest/standard_generators.html)
- specifically, the human population powerlaw with cutoff model is now [built-in](https://pyepydemic.readthedocs.io/en/latest/standard_generators.html#epydemic.PLCNetwork)

I'm intending to re-write the book's code to match the new version as soon as I get a chance: at present I'm deep into using the code to look at signal processing, so it's been put on the back burner for a couple of months. In the meantime, I'd be happy to help out if you want to try running with the latest code, and would love to hear about what you're interest are in epidemic modelling.

Cheers,

-- Simon

**Comment by FeynmanDNA** [comment]
Thank you professor dobson!

I got to know your epydemic library through your YouTube talk given at IMAmaths (https://www.youtube.com/watch?v=apR_qD2tOkU). And I didn't expect so much implementations and design considerations can be given into a proper simulation. Your explanation on the Gillipsie and other simulation techniques are very helpful! I have learned a lot from your talk and the book.
